fix update method body and signature
 - update method was throwing exception ` AttributeError: 'Team' object has no attribute 'get'` as `attrs` and `instance` where swapped
 - `attrs` shouldn't be optional
 - fix updating to new team name
 - save to database upon updating